### ISSUE TITLE
Widget ei lataa kohteita jokaisella eteenpäinselauksella

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos-widget-finna#6]
Kun valitaan sivu  jolla on tarpeeksi paljon kohteita finna-widgetin kautta, kuten
http://www.yso.fi/onto/yso/p2225
ja selataan widgettiä eteenpäin 4-5 kertaa, saadaan tilanne missä joka toinen näkymä eteenpäinselauksella on tyhjä. Kuitenkin tyhjään näkymään lataamattajääneet kohteet saa näkymään kun widgettiä selataan takaisinpäin.

**Comment by kouralex** [comment]
Jos toistuu, avaa uusi ilmoitus. Vaikuttaa nyt toimivan tulevan 2.7:n kanssa tekemäni muutoksen kanssa.
