### ISSUE TITLE
Unhandled exception on some concept pages

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos-widget-finna#7]
According to [this Skosmos issue](https://github.com/NatLibFi/Skosmos/issues/876) the Finna widget causes an unhandled JS exception for some concept pages. This must be tracked down and fixed in the widget code.

**Comment by kouralex** [comment]
[This](https://github.com/NatLibFi/Skosmos-widget-finna/commit/4f5bc3feba14e14ef91569554d377091ade44b89) fixes this issue partly at least for the forthcoming Skosmos 2.7 (not working on 2.6 though).

Closing this in favor of new, clear cases of unhandled exceptions.
